[[drone]]
id = 1
connected_node_ids = [2, 4]  
pdr = 0.05  

[[drone]]
id = 2
connected_node_ids = [1, 3]  
pdr = 0.04  

[[drone]]
id = 3
connected_node_ids = [2, 5]  
pdr = 0.06  

[[client]]
id = 4
connected_drone_ids = [1]  

[[server]]
id = 5
connected_drone_ids = [3]  
