[[drone]]
id = 1
connected_node_ids = [2, 3, 7]  
pdr = 0.00  

[[drone]]
id = 2
connected_node_ids = [1, 4, 5]  
pdr = 0.00  

[[drone]]
id = 3
connected_node_ids = [1, 6]  
pdr = 0.00

[[drone]]
id = 4
connected_node_ids = [2, 8]  
pdr = 0.00 

[[drone]]
id = 5
connected_node_ids = [2, 8]  
pdr = 0.00  

[[drone]]
id = 6
connected_node_ids = [3, 8]  
pdr = 0.00 

[[client]]
id = 7
connected_drone_ids = [1]  

[[server]]
id = 8
connected_drone_ids = [4, 5, 6]  
